site_name: Thermott
theme:
  name: material
  custom_dir: overrides
  icon:
    logo: logo
  favicon: otter.png
  features:
    - navigation.sections

nav:
  - Experiment:
    - '04dataacquisition.md'
    - '05troubleshooting.md'
  - Analysis:
    - '01rawdata.md'
    - '02experimentinfo.md'
    - '03fitbinding.md'
  - '06citation.md'

    
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - admonition
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - js/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css